### ISSUE TITLE
Z-index of marker timer

### ISSUE THREAD

**Issue by Spencersss** [Cyborger1/mlm-upper-level-markers#1]
Not sure if it is possible, but currently the text is covered by the skill icon for mining when the text is under the icon. Wanted to have the option to have the text draw over the icons. 
![image](https://user-images.githubusercontent.com/13088535/106383584-ea2c1800-6394-11eb-90fe-d6001ce1a44a.png)

**Comment by Cyborger1** [comment]
I have added a config field to force the overlay to be on a higher rendering layer than the Motherlode plugin.

As both are currently on the same layer, one may be above the other depending on the order they're loaded.

You can fix it on your end right now by simply turning the plugin off and back on though, as it will now be after the Motherlode plugin in the rendering order. With the new setting though, it should ensure that it always appears on top no matter what, but it may cause some issues with other overlays. Turning the new setting on and off can also be used to force the order without having to turn the plugin off.
